# База данных
#### `CREATE` 
Создать объект: Таблица,база,индекс
```sqlу
CREATE TABLE employees(
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
salary NUMERIC
)
```
#### `TABLE` 
Указывает, что создается или изменяется таблица
```sqlу
CREATE TABLE departaments(
id SERIAL PRIMARY KEY,
name TEXT 
)
```

#### `ALTER` 
изменяет существующий объект
```sqlу
ALTER TABLE employees
ADD COLUMN email TEXT,

```

### ADD
Добавляет колонку, ограничения
```sql
ALTER TABLE employees
ADD COLUMN phone TEXT;
```

### DROP
Удаляет объект (таблицу)
```sql
DROP TABLE projects;
```
### 'IF EXISTS'

Позволяет избежать ошибки, если объекта нет
```sql
DROP TABLE IF EXISTS old_projects;
```
### 'IF NOT EXISTS'
Создает объект только если он еще не существует
```sql
CREATE TABLE IF NOT EXISTS departaments( id SERIAL PRIMARY KEY, name TEXT);
```
### 'RENAME'
Переименовывает объект
```sql
ALTER TABLE employees
RENAME COLUMN name to full_name;
```

### 'TRANCATE'
Быстро очищает таблицу
```sql
TRANCATE TABLE projects;
```

## 2. Работа с данными
### 'SELECT'
Выбирает данные
```sql
SELECT name, salary FROM employees;
```
### 'FROM'
Указыввет источник даннхы
```sql
SELECT name, salary FROM employees;
```
### 'INSERT'
Добавляент строик
```sql name,
INSERT INTO departaments(name)
VALUES ('it'),('HR'), ('Finance');
```
### 'INTO'
Указыввет куда нужно вставлять данные
```sql name,
INSERT INTO employees(name,salary,departament)

VALUES ('Анна',12000, 1);
```

### 'VALUES'
Передвает конкретные зхнаычения
```sql name,
INSERT INTO projects(name,employee_id,budget)

VALUES ('CRM System', 1,500000);
```
